### Подключение библиотек

In [1]:
from bs4 import BeautifulSoup as bs

In [2]:
import requests

In [2]:
import pandas as pd

### Получение информаций

In [4]:
url = 'https://w140.zona.plus/movies/' 
page = requests.get(url)

In [5]:
page.status_code

200

In [6]:
soup = bs(page.text, 'html.parser')

In [7]:
page.text

'<!DOCTYPE html>\n<html lang="ru">\n<head>\n  <meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">\n<meta name="mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<link rel="icon" type="image/png" href="/favicon-192x192.png" sizes="192x192">\n<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">\n<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">\n<link rel="apple-touch-icon" href="/apple-touch-icon.png">\n<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">\n    <link rel="canonical" href="https://w140.zona.plus/movies">\n<meta name="msapplication-TileColor" content="#2d89ef">\n<meta name="msapplication-TileImage" content="/mstile-144x144.png">\n<title>zona.plus (ex zona.mobi) - смотреть фильмы 2026 онлайн, смотреть новинки в хорошем качестве</title>\n<meta name="description" content="Смотреть новинки 2026 года в хорошем качестве, лучшие фильмы 2026 онлайн - zona.plus (ex zona.mobi)"/>\n<link rel="stylesheet" type="text/css" href="/build/bundle-3d65761d1faa4b5cc6a0.css" >\n<!--link rel="stylesheet" type="text/css" href="/css/player.css?1769403672" -->\n\n\n    <link rel="next" href="/movies?page=2">\n\n  <script>\n      window._app = {\n              version: \'1769403672\',\n              isMobile: false\n          };\n  </script>\n\n  <script type="text/javascript">\n    // IE9 fix\n    if(!window.console) {\n      var console = {\n        log : function(){},\n        warn : function(){},\n        error : function(){},\n        time : function(){},\n        timeEnd : function(){}\n      }\n    }\n  </script>\n\n</head>\n<body>\n\n<div class="l-container">\n            <header class="header">\n    <div class="l-wrap header-container">\n    <div class="header-banner">\n  <span class="header-banner-text">Новый дизайн. Без&nbsp;рекламы. HD&nbsp;качество, выбор озвучки</span>\n  <a class="header-banner-link" rel="nofollow" href="https://w1.zona.im/" target="_blank">Перейти</a>\n</div>\n<nav class="header-nav">\n  <a class="js-index header-nav-item is-index " title="На главную zona.plus (ex zona.mobi)" href="/">Zona</a>\n<a class="js-movies header-nav-item is-selected" title="Все фильмы на zona.plus (ex zona.mobi)" href="/movies">Фильмы</a>\n<a class="js-tvseries header-nav-item " title="Все сериалы на zona.plus (ex zona.mobi)" href="/tvseries">Сериалы</a></nav>\n<div class="js-module-search">\n  <label class="header-search-btn" for="search-input" tabindex="0" title="Поиск"></label>\n  <div class="header-search-line">\n    <form class="header-search-form" action="/search-form">\n      <span class="header-back-btn" title="Назад"></span>\n      <input autocomplete="off" name="query" placeholder="Поиск фильмов и сериалов" value="" class="header-search-line-input" id="search-input" placeholder="Поиск фильмов и сериалов">\n      <span class="header-search-line-submit" title="Искать" type="submit"></span>\n      <ul class="suggest">\n      </ul>\n    </form>\n  </div>\n</div>\n<div>\n</header>\n    \n    <main class="l-content">\n      <div class="l-wrap">\n        <div class="js-filters">\n  \n<form class="filters js-filters-form" action="/movies/filter/" method="get">\n  <div class="filter-items">\n    <span class="filters-item">\n      <select class="filters-item-select " id="filter-id-genreId" name="genre">\n        <option value="0"  selected="selected" label="Жанры">Жанры</option>\n                              <option value="genre-drama" label="драма">драма</option>\n                      <option value="genre-komediia" label="комедия">комедия</option>\n                      <option value="genre-triller" label="триллер">триллер</option>\n                      <option value="genre-melodrama" label="мелодрама">мелодрама</option>\n                      <option value="genre-boevik" label="боевик">боевик</option>\n                      <option value="genre-kriminal" label="криминал">криминал</option>\n                      <option value="genre-uzhasy" label="ужасы">ужасы</option>\n                      <option value="genre-prikliucheniia" label="приключения">приключения</option>\n                      <option value="genre-detektiv" label="детектив">детектив</option>\n                      <option value="genre-fantastika" label="фантастика">фантастика</option>\n                      <option value="genre-fentezi" label="фэнтези">фэнтези</option>\n                      <option value="genre-semeinyi" label="семейный">семейный</option>\n                      <option value="genre-multfilm" label="мультфильм">мультфильм</option>\n                      <option value="genre-korotkometrazhka" label="короткометражка">короткометражка</option>\n                      <option value="genre-voennyi" label="военный">военный</option>\n                      <option value="genre-istoriia" label="история">история</option>\n                      <option value="genre-dokumentalnyi" label="документальный">документальный</option>\n                      <option value="genre-biografiia" label="биография">биография</option>\n                      <option value="genre-miuzikl" label="мюзикл">мюзикл</option>\n                      <option value="genre-muzyka" label="музыка">музыка</option>\n                      <option value="genre-vestern" label="вестерн">вестерн</option>\n                      <option value="genre-sport" label="спорт">спорт</option>\n                      <option value="genre-detskii" label="детский">детский</option>\n                      <option value="genre-anime" label="аниме">аниме</option>\n                      <option value="genre-film-nuar" label="фильм-нуар">фильм-нуар</option>\n                      <option value="genre-realnoe-tv" label="реальное ТВ">реальное ТВ</option>\n                      <option value="genre-kontcert" label="концерт">концерт</option>\n                      <option value="genre-novosti" label="новости">новости</option>\n                      <option value="genre-igra" label="игра">игра</option>\n                      <option value="genre-tok-shou" label="ток-шоу">ток-шоу</option>\n                        </select>\n          </span>\n\n    <span class="filters-item" >\n      <select  class="filters-item-select " id="filter-id-year" name="year">\n        <option value="0"  selected="selected" label="Год">Год</option>\n        <option value="year-2026" label="2026">2026</option>\n        <option value="year-2025" label="2025">2025</option>\n        <option value="year-2024" label="2024">2024</option>\n        <option value="year-2023" label="2023">2023</option>\n        <option value="year-2022" label="2022">2022</option>\n        <option value="year-2021" label="2021">2021</option>\n        <option value="year-2020" label="2020">2020</option>\n        <option value="year-2019" label="2019">2019</option>\n        <option value="year-2018" label="2018">2018</option>\n        <option value="year-2017" label="2017">2017</option>\n        <option value="year-2016" label="2016">2016</option>\n        <option value="year-2015" label="2015">2015</option>\n        <option value="year-2014" label="2014">2014</option>\n        <option value="year-2013" label="2013">2013</option>\n        <option value="year-2012" label="2012">2012</option>\n        <option value="year-2011" label="2011">2011</option>\n        <option value="year-2010" label="2010">2010</option>\n        <option value="year-2000s" label="2000-е">2000-е</option>\n        <option value="year-90s" label="90-е">90-е</option>\n        <option value="year-80s" label="80-е">80-е</option>\n        <option value="year-70s" label="70-е">70-е</option>\n        <option value="year-60s" label="60-е">60-е</option>\n        <option value="year-50s" label="50-е">50-е</option>\n        <option value="year-40s" label="40-е">40-е</option>\n        <option value="year-old" label="до 40-х">до 40-х</option>\n      </select>\n          </span>\n\n    <span class="filters-item">\n      <select class="filters-item-select " id="filter-id-country_id" name="country">\n        <option value="0"  selected="selected" label="Страна">Страна</option>\n                              <option value="country-ssha"  label="США">США</option>\n                      <option value="country-rossiia"  label="Россия">Россия</option>\n                      <option value="country-frantciia"  label="Франция">Франция</option>\n                      <option value="country-velikobritaniia"  label="Великобритания">Великобритания</option>\n                      <option value="country-kanada"  label="Канада">Канада</option>\n                      <option value="country-germaniia"  label="Германия">Германия</option>\n                      <option value="country-italiia"  label="Италия">Италия</option>\n                      <option value="country-indiia"  label="Индия">Индия</option>\n                      <option value="country-iaponiia"  label="Япония">Япония</option>\n                      <option value="country-ispaniia"  label="Испания">Испания</option>\n                      <option value="country-gonkong"  label="Гонконг">Гонконг</option>\n                      <option value="country-koreia-iuzhnaia"  label="Корея Южная">Корея Южная</option>\n                      <option value="country-kitai"  label="Китай">Китай</option>\n                      <option value="country-belgiia"  label="Бельгия">Бельгия</option>\n                      <option value="country-avstraliia"  label="Австралия">Австралия</option>\n                      <option value="country-polsha"  label="Польша">Польша</option>\n                      <option value="country-shvetciia"  label="Швеция">Швеция</option>\n                      <option value="country-meksika"  label="Мексика">Мексика</option>\n                      <option value="country-chekhiia"  label="Чехия">Чехия</option>\n                      <option value="country-daniia"  label="Дания">Дания</option>\n                      <option value="country-niderlandy"  label="Нидерланды">Нидерланды</option>\n                      <option value="country-irlandiia"  label="Ирландия">Ирландия</option>\n                      <option value="country-shveitcariia"  label="Швейцария">Швейцария</option>\n                      <option value="country-ukraina"  label="Украина">Украина</option>\n                      <option value="country-argentina"  label="Аргентина">Аргентина</option>\n                      <option value="country-norvegiia"  label="Норвегия">Норвегия</option>\n                      <option value="country-vengriia"  label="Венгрия">Венгрия</option>\n                      <option value="country-avstriia"  label="Австрия">Австрия</option>\n                      <option value="country-braziliia"  label="Бразилия">Бразилия</option>\n                      <option value="country-taivan"  label="Тайвань">Тайвань</option>\n                        </select>\n          </span>\n\n    <span class="filters-item">\n      <select class="filters-item-select " id="filter-id-rating" name="rating">\n        <option value="0"  selected="selected" label="Рейтинг">Рейтинг</option>\n                  <option value="rating-9" label="от 9">от 9</option>\n                    <option value="rating-8" label="от 8">от 8</option>\n                    <option value="rating-7" label="от 7">от 7</option>\n                    <option value="rating-6" label="от 6">от 6</option>\n                    <option value="rating-5" label="от 5">от 5</option>\n                    <option value="rating-4" label="от 4">от 4</option>\n                    <option value="rating-3" label="от 3">от 3</option>\n                    <option value="rating-2" label="от 2">от 2</option>\n                    <option value="rating-1" label="от 1">от 1</option>\n                </select>\n          </span>\n\n    <span class="filters-item" >\n      <select class="filters-item-select " id="filter-id-sort" name="sort">\n        <option value="0"  selected="selected" label="По популярности">По популярности</option>\n        <option value="sort-rating" label="По рейтингу">По рейтингу</option>\n        <option value="sort-date" label="По дате выхода">По дате выхода</option>\n      </select>\n          </span>\n  </div>\n</form>\n\n</div>\n<div class="results-wrap">\n      <h1 class="results-top-title ">Популярные фильмы </h1>\n<div class="hide js-pageInfo" data-current="1" data-total="1292"></div>\n<ul class="results">\n            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img3.zonapic.com/images/film_240/6450/6450546.jpg">\n  <a class="results-item" itemprop="url" href="/movies/ograblenie-v-los-andzhelese" title="Ограбление в Лос-Анджелесе (2026)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img3.zonapic.com/images/film_240/6450/6450546.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Ограбление в Лос-Анджелесе</div>\n                                                <span class="results-item-rating">\n                        <span>6.7</span>\n                    </span>\n                                  <span class="results-item-year">2026</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img1.zonapic.com/images/film_240/463/463492.jpg">\n  <a class="results-item" itemprop="url" href="/movies/udachi-veselya-ne-sdohni" title="Удачи, веселья, не сдохни (2025)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img1.zonapic.com/images/film_240/463/463492.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Удачи, веселья, не сдохни</div>\n                                                <span class="results-item-rating">\n                        <span>7.0</span>\n                    </span>\n                                  <span class="results-item-year">2025</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img4.zonapic.com/images/film_240/5461/5461947.jpg">\n  <a class="results-item" itemprop="url" href="/movies/ostrye-kozyrki-bessmertnyi-chelovek" title="Острые козырьки: Бессмертный человек (2026)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img4.zonapic.com/images/film_240/5461/5461947.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Острые козырьки: Бессмертный человек</div>\n                                                <span class="results-item-rating">\n                        <span>6.7</span>\n                    </span>\n                                  <span class="results-item-year">2026</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img1.zonapic.com/images/film_240/5379/5379012.jpg">\n  <a class="results-item" itemprop="url" href="/movies/cheburashka-2" title="Чебурашка 2 (2025)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img1.zonapic.com/images/film_240/5379/5379012.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Чебурашка 2</div>\n                                                <span class="results-item-rating">\n                        <span>7.6</span>\n                    </span>\n                                  <span class="results-item-year">2025</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img4.zonapic.com/images/film_240/5613/5613471.jpg">\n  <a class="results-item" itemprop="url" href="/movies/korol-i-shut-navsegda" title="Король и Шут. Навсегда (2026)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img4.zonapic.com/images/film_240/5613/5613471.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Король и Шут. Навсегда</div>\n                                                <span class="results-item-rating">\n                        <span>6.4</span>\n                    </span>\n                                  <span class="results-item-year">2026</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img4.zonapic.com/images/film_240/10207/10207191.jpg">\n  <a class="results-item" itemprop="url" href="/movies/svoi-ballada-o-voine" title="Свои. Баллада о войне (2025)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img4.zonapic.com/images/film_240/10207/10207191.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Свои. Баллада о войне</div>\n                                                <span class="results-item-rating">\n                        <span>6.9</span>\n                    </span>\n                                  <span class="results-item-year">2025</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img3.zonapic.com/images/film_240/570/570402.jpg">\n  <a class="results-item" itemprop="url" href="/movies/avatar-plamya-i-pepel" title="Аватар: Пламя и пепел (2025)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img3.zonapic.com/images/film_240/570/570402.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Аватар: Пламя и пепел</div>\n                                                <span class="results-item-rating">\n                        <span>7.6</span>\n                    </span>\n                                  <span class="results-item-year">2025</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="https://img4.zonapic.com/images/film_240/6553/6553075.jpg">\n  <a class="results-item" itemprop="url" href="/movies/levsha-2026" title="Левша (2026)">\n    <div class="result-item-preview-wrap">\n      <div class="result-item-preview fadeIn animated " style="background-image: url(https://img4.zonapic.com/images/film_240/6553/6553075.jpg), url(\'/img/nocover.png\');"></div>\n    </div>\n    <div class="result-item-footer">\n      <div class="results-item-title" itemprop="name">Левша</div>\n                                                <span class="results-item-rating">\n                        <span>7.3</span>\n                    </span>\n                                  <span class="results-item-year">2026</span>\n    </div>\n  </a>\n</li>            <li class="results-item-wrap" itemscope itemtype="http://schema.org/Movie">\n  <meta itemprop="image" content="htt

In [8]:
soup

<!DOCTYPE html>

<html lang="ru">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" name="viewport"/>
<meta content="yes" name="mobile-web-app-capable"/>
<meta content="yes" name="apple-mobile-web-app-capable"/>
<link href="/favicon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/apple-touch-icon.png" rel="apple-touch-icon"/>
<link href="/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://w140.zona.plus/movies" rel="canonical"/>
<meta content="#2d89ef" name="msapplication-TileColor"/>
<meta content="/mstile-144x144.png" name="msapplication-TileImage"/>
<title>zona.plus (ex zona.mobi) - смотреть фильмы 2026 онлайн, смотреть новинки в хорошем качестве</title>
<meta content="Смотреть новинки 2026 года в хорошем качестве, лучшие фильмы 2026 онлайн - zona.plus (ex zona.mobi)" name="description">
<link href="/build/bundle-3d65761d1faa4b5cc6a0.css" rel="stylesheet" type="text/css"/>
<!--link rel="stylesheet" type="text/css" href="/css/player.css?1769403672" -->
<link href="/movies?page=2" rel="next"/>
<script>
      window._app = {
              version: '1769403672',
              isMobile: false
          };
  </script>
<script type="text/javascript">
    // IE9 fix
    if(!window.console) {
      var console = {
        log : function(){},
        warn : function(){},
        error : function(){},
        time : function(){},
        timeEnd : function(){}
      }
    }
  </script>
</meta></head>
<body>
<div class="l-container">
<header class="header">
<div class="l-wrap header-container">
<div class="header-banner">
<span class="header-banner-text">Новый дизайн. Без рекламы. HD качество, выбор озвучки</span>
<a class="header-banner-link" href="https://w1.zona.im/" rel="nofollow" target="_blank">Перейти</a>
</div>
<nav class="header-nav">
<a class="js-index header-nav-item is-index" href="/" title="На главную zona.plus (ex zona.mobi)">Zona</a>
<a class="js-movies header-nav-item is-selected" href="/movies" title="Все фильмы на zona.plus (ex zona.mobi)">Фильмы</a>
<a class="js-tvseries header-nav-item" href="/tvseries" title="Все сериалы на zona.plus (ex zona.mobi)">Сериалы</a></nav>
<div class="js-module-search">
<label class="header-search-btn" for="search-input" tabindex="0" title="Поиск"></label>
<div class="header-search-line">
<form action="/search-form" class="header-search-form">
<span class="header-back-btn" title="Назад"></span>
<input autocomplete="off" class="header-search-line-input" id="search-input" name="query" placeholder="Поиск фильмов и сериалов" value=""/>
<span class="header-search-line-submit" title="Искать" type="submit"></span>
<ul class="suggest">
</ul>
</form>
</div>
</div>
<div>
</div></div></header>
<main class="l-content">
<div class="l-wrap">
<div class="js-filters">
<form action="/movies/filter/" class="filters js-filters-form" method="get">
<div class="filter-items">
<span class="filters-item">
<select class="filters-item-select" id="filter-id-genreId" name="genre">
<option label="Жанры" selected="selected" value="0">Жанры</option>
<option label="драма" value="genre-drama">драма</option>
<option label="комедия" value="genre-komediia">комедия</option>
<option label="триллер" value="genre-triller">триллер</option>
<option label="мелодрама" value="genre-melodrama">мелодрама</option>
<option label="боевик" value="genre-boevik">боевик</option>
<option label="криминал" value="genre-kriminal">криминал</option>
<option label="ужасы" value="genre-uzhasy">ужасы</option>
<option label="приключения" value="genre-prikliucheniia">приключения</option>
<option label="детектив" value="genre-detektiv">детектив</option>
<option label="фантастика" value="genre-fantastika">фантастика</option>
<option label="фэнтези" value="genre-fentezi">фэнтези</option>
<option label="семейный" value="genre-semeinyi">семейный</option>
<option label="мультфильм" value="genre-multfilm">мультфильм</option>
<option label="короткометражка" value="genre-korotkometrazhka">короткометражка</option>
<option label="военный" value="genre-voennyi">военный</option>
<option label="история" value="genre-istoriia">история</option>
<option label="документальный" value="genre-dokumentalnyi">документальный</option>
<option label="биография" value="genre-biografiia">биография</option>
<option label="мюзикл" value="genre-miuzikl">мюзикл</option>
<option label="музыка" value="genre-muzyka">музыка</option>
<option label="вестерн" value="genre-vestern">вестерн</option>
<option label="спорт" value="genre-sport">спорт</option>
<option label="детский" value="genre-detskii">детский</option>
<option label="аниме" value="genre-anime">аниме</option>
<option label="фильм-нуар" value="genre-film-nuar">фильм-нуар</option>
<option label="реальное ТВ" value="genre-realnoe-tv">реальное ТВ</option>
<option label="концерт" value="genre-kontcert">концерт</option>
<option label="новости" value="genre-novosti">новости</option>
<option label="игра" value="genre-igra">игра</option>
<option label="ток-шоу" value="genre-tok-shou">ток-шоу</option>
</select>
</span>
<span class="filters-item">
<select class="filters-item-select" id="filter-id-year" name="year">
<option label="Год" selected="selected" value="0">Год</option>
<option label="2026" value="year-2026">2026</option>
<option label="2025" value="year-2025">2025</option>
<option label="2024" value="year-2024">2024</option>
<option label="2023" value="year-2023">2023</option>
<option label="2022" value="year-2022">2022</option>
<option label="2021" value="year-2021">2021</option>
<option label="2020" value="year-2020">2020</option>
<option label="2019" value="year-2019">2019</option>
<option label="2018" value="year-2018">2018</option>
<option label="2017" value="year-2017">2017</option>
<option label="2016" value="year-2016">2016</option>
<option label="2015" value="year-2015">2015</option>
<option label="2014" value="year-2014">2014</option>
<option label="2013" value="year-2013">2013</option>
<option label="2012" value="year-2012">2012</option>
<option label="2011" value="year-2011">2011</option>
<option label="2010" value="year-2010">2010</option>
<option label="2000-е" value="year-2000s">2000-е</option>
<option label="90-е" value="year-90s">90-е</option>
<option label="80-е" value="year-80s">80-е</option>
<option label="70-е" value="year-70s">70-е</option>
<option label="60-е" value="year-60s">60-е</option>
<option label="50-е" value="year-50s">50-е</option>
<option label="40-е" value="year-40s">40-е</option>
<option label="до 40-х" value="year-old">до 40-х</option>
</select>
</span>
<span class="filters-item">
<select class="filters-item-select" id="filter-id-country_id" name="country">
<option label="Страна" selected="selected" value="0">Страна</option>
<option label="США" value="country-ssha">США</option>
<option label="Россия" value="country-rossiia">Россия</option>
<option label="Франция" value="country-frantciia">Франция</option>
<option label="Великобритания" value="country-velikobritaniia">Великобритания</option>
<option label="Канада" value="country-kanada">Канада</option>
<option label="Германия" value="country-germaniia">Германия</option>
<option label="Италия" value="country-italiia">Италия</option>
<option label="Индия" value="country-indiia">Индия</option>
<option label="Япония" value="country-iaponiia">Япония</option>
<option label="Испания" value="country-ispaniia">Испания</option>
<option label="Гонконг" value="country-gonkong">Гонконг</option>
<option label="Корея Южная" value="country-koreia-iuzhnaia">Корея Южная</option>
<option label="Китай" value="country-kitai">Китай</option>
<option label="Бельгия" value="country-belgiia">Бельгия</option>
<option label="Австралия" value="country-avstraliia">Австралия</option>
<option label="Польша" value="country-polsha">Польша</option>
<option label="Швеция" value="country-shvetciia">Швеция</option>
<option label="Мексика" value="country-meksika">Мексика</option>
<option label="Чехия" value="country-chekhiia">Чехия</option>
<option label="Дания" value="country-daniia">Дания</option>
<option label="Нидерланды" value="country-niderlandy">Нидерланды</option>
<option label="Ирландия" value="country-irlandiia">Ирландия</option>
<option label="Швейцария" value="country-shveitcariia">Швейцария</option>
<option label="Украина" value="country-ukraina">Украина</option>
<option label="Аргентина" value="country-argentina">Аргентина</option>
<option label="Норвегия" value="country-norvegiia">Норвегия</option>
<option label="Венгрия" value="country-vengriia">Венгрия</option>
<option label="Австрия" value="country-avstriia">Австрия</option>
<option label="Бразилия" value="country-braziliia">Бразилия</option>
<option label="Тайвань" value="country-taivan">Тайвань</option>
</select>
</span>
<span class="filters-item">
<select class="filters-item-select" id="filter-id-rating" name="rating">
<option label="Рейтинг" selected="selected" value="0">Рейтинг</option>
<option label="от 9" value="rating-9">от 9</option>
<option label="от 8" value="rating-8">от 8</option>
<option label="от 7" value="rating-7">от 7</option>
<option label="от 6" value="rating-6">от 6</option>
<option label="от 5" value="rating-5">от 5</option>
<option label="от 4" value="rating-4">от 4</option>
<option label="от 3" value="rating-3">от 3</option>
<option label="от 2" value="rating-2">от 2</option>
<option label="от 1" value="rating-1">от 1</option>
</select>
</span>
<span class="filters-item">
<select class="filters-item-select" id="filter-id-sort" name="sort">
<option label="По популярности" selected="selected" value="0">По популярности</option>
<option label="По рейтингу" value="sort-rating">По рейтингу</option>
<option label="По дате выхода" value="sort-date">По дате выхода</option>
</select>
</span>
</div>
</form>
</div>
<div class="results-wrap">
<h1 class="results-top-title">Популярные фильмы </h1>
<div class="hide js-pageInfo" data-current="1" data-total="1292"></div>
<ul class="results">
<li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img3.zonapic.com/images/film_240/6450/6450546.jpg" itemprop="image"/>
<a class="results-item" href="/movies/ograblenie-v-los-andzhelese" itemprop="url" title="Ограбление в Лос-Анджелесе (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img3.zonapic.com/images/film_240/6450/6450546.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Ограбление в Лос-Анджелесе</div>
<span class="results-item-rating">
<span>6.7</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img1.zonapic.com/images/film_240/463/463492.jpg" itemprop="image"/>
<a class="results-item" href="/movies/udachi-veselya-ne-sdohni" itemprop="url" title="Удачи, веселья, не сдохни (2025)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img1.zonapic.com/images/film_240/463/463492.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Удачи, веселья, не сдохни</div>
<span class="results-item-rating">
<span>7.0</span>
</span>
<span class="results-item-year">2025</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img4.zonapic.com/images/film_240/5461/5461947.jpg" itemprop="image"/>
<a class="results-item" href="/movies/ostrye-kozyrki-bessmertnyi-chelovek" itemprop="url" title="Острые козырьки: Бессмертный человек (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img4.zonapic.com/images/film_240/5461/5461947.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Острые козырьки: Бессмертный человек</div>
<span class="results-item-rating">
<span>6.7</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img1.zonapic.com/images/film_240/5379/5379012.jpg" itemprop="image"/>
<a class="results-item" href="/movies/cheburashka-2" itemprop="url" title="Чебурашка 2 (2025)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img1.zonapic.com/images/film_240/5379/5379012.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Чебурашка 2</div>
<span class="results-item-rating">
<span>7.6</span>
</span>
<span class="results-item-year">2025</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img4.zonapic.com/images/film_240/5613/5613471.jpg" itemprop="image"/>
<a class="results-item" href="/movies/korol-i-shut-navsegda" itemprop="url" title="Король и Шут. Навсегда (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img4.zonapic.com/images/film_240/5613/5613471.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Король и Шут. Навсегда</div>
<span class="results-item-rating">
<span>6.4</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img4.zonapic.com/images/film_240/10207/10207191.jpg" itemprop="image"/>
<a class="results-item" href="/movies/svoi-ballada-o-voine" itemprop="url" title="Свои. Баллада о войне (2025)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img4.zonapic.com/images/film_240/10207/10207191.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Свои. Баллада о войне</div>
<span class="results-item-rating">
<span>6.9</span>
</span>
<span class="results-item-year">2025</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img3.zonapic.com/images/film_240/570/570402.jpg" itemprop="image"/>
<a class="results-item" href="/movies/avatar-plamya-i-pepel" itemprop="url" title="Аватар: Пламя и пепел (2025)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img3.zonapic.com/images/film_240/570/570402.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Аватар: Пламя и пепел</div>
<span class="results-item-rating">
<span>7.6</span>
</span>
<span class="results-item-year">2025</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img4.zonapic.com/images/film_240/6553/6553075.jpg" itemprop="image"/>
<a class="results-item" href="/movies/levsha-2026" itemprop="url" title="Левша (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img4.zonapic.com/images/film_240/6553/6553075.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Левша</div>
<span class="results-item-rating">
<span>7.3</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img3.zonapic.com/images/film_240/5364/5364826.jpg" itemprop="image"/>
<a class="results-item" href="/movies/krik-7" itemprop="url" title="Крик 7 (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img3.zonapic.com/images/film_240/5364/5364826.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Крик 7</div>
<span class="results-item-rating">
<span>5.9</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img1.zonapic.com/images/film_240/5453/5453060.jpg" itemprop="image"/>
<a class="results-item" href="/movies/kaznit-nelzya-pomilovat-2026" itemprop="url" title="Казнить нельзя помиловать (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img1.zonapic.com/images/film_240/5453/5453060.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Казнить нельзя помиловать</div>
<span class="results-item-rating">
<span>6.6</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img3.zonapic.com/images/film_240/6398/6398650.jpg" itemprop="image"/>
<a class="results-item" href="/movies/grozovoi-pereval-2026" itemprop="url" title="Грозовой перевал (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img3.zonapic.com/images/film_240/6398/6398650.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Грозовой перевал</div>
<span class="results-item-rating">
<span>6.5</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img1.zonapic.com/images/film_240/1382/1382256.jpg" itemprop="image"/>
<a class="results-item" href="/movies/proekt-konets-sveta" itemprop="url" title="Проект «Конец света» (2026)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img1.zonapic.com/images/film_240/1382/1382256.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Проект «Конец света»</div>
<span class="results-item-rating">
<span>8.1</span>
</span>
<span class="results-item-year">2026</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img1.zonapic.com/images/film_240/7527/7527356.jpg" itemprop="image"/>
<a class="results-item" href="/movies/tri-bogatyrya-i-svet-klinom" itemprop="url" title="Три богатыря и свет клином (2025)">
<div class="result-item-preview-wrap">
<div class="result-item-preview fadeIn animated" style="background-image: url(https://img1.zonapic.com/images/film_240/7527/7527356.jpg), url('/img/nocover.png');"></div>
</div>
<div class="result-item-footer">
<div class="results-item-title" itemprop="name">Три богатыря и свет клином</div>
<span class="results-item-rating">
<span>7.6</span>
</span>
<span class="results-item-year">2025</span>
</div>
</a>
</li> <li class="results-item-wrap" itemscope="" itemtype="http://schema.org/Movie">
<meta content="https://img2.zonapic.com/images/film_240/8989/8989285.jpg" itemprop="image"/>
<a class="results-item" href="/movies/dospehi" itemprop="url" title="Доспехи (2025)">
<div class="result-item-preview-wrap">

In [9]:
result_list = {'title': [], 'genre': [], 'year': [], 'country': [], 'rating': [], 'description': []}

### Алгоритм

In [10]:
import time
import random

base_url = 'https://w140.zona.plus'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}

session = requests.Session()
session.headers.update(headers)

pagenum = 1
max_movies = 250 
count = 0

while count < max_movies:
    url = f'{base_url}/movies?page={pagenum}'
    try:
        response = session.get(url, timeout=15)
        soup = bs(response.text, 'html.parser')
        movie_links = soup.find_all('a', class_='results-item')
        if not movie_links: break

        for movie in movie_links:
            if count >= max_movies: break
            
            title = movie.find('div', class_='results-item-title').text.strip()
            year = movie.find('span', class_='results-item-year').text.strip()
            rating = movie.find('span', class_='results-item-rating').text.strip() if movie.find('span', class_='results-item-rating') else "0.0"
            movie_url = base_url + movie.get('href')

            try:
                m_res = session.get(movie_url, timeout=10)
                m_soup = bs(m_res.text, 'html.parser')

                movie_genre = "Не указан"
                movie_country = "Не указана"

                dts = m_soup.find_all('dt')
                for dt in dts:
                    label = dt.text.strip()
                    dd = dt.find_next_sibling('dd')
                    if dd:
                        clean_value = ' '.join(dd.text.replace('\n', ' ').split())
                        
                        if "Жанр" in label:
                            movie_genre = clean_value
                        elif "Страна" in label:
                            movie_country = clean_value

                desc_el = m_soup.find(attrs={"itemprop": "description"})
                description = ' '.join(desc_el.text.replace('\n', ' ').split()) if desc_el else "Нет описания"

                result_list['title'].append(title)
                result_list['year'].append(year)
                result_list['rating'].append(rating)
                result_list['genre'].append(movie_genre)
                result_list['country'].append(movie_country)
                result_list['description'].append(description)

                count += 1
                print(f"[{count}] {title} | {movie_genre} | {movie_country}")
                
            except Exception: continue
            time.sleep(1)
        pagenum += 1
    except Exception: break

df = pd.DataFrame(result_list)
df.to_csv('zona_data.csv', index=False, encoding='utf-8-sig')
print("\n Файл 'zona_clean_data.csv' готов")

[1] Ограбление в Лос-Анджелесе | криминал, драма, триллер | США , Великобритания
[2] Удачи, веселья, не сдохни | боевик, драма, комедия, фантастика | США , Германия
[3] Острые козырьки: Бессмертный человек | история, драма, криминал | США , Франция , Великобритания
[4] Чебурашка 2 | фэнтези, комедия, семейный | Россия
[5] Король и Шут. Навсегда | музыка, приключения, драма, комедия, фэнтези | Россия
[6] Свои. Баллада о войне | драма, военный | Россия
[7] Аватар: Пламя и пепел | приключения, боевик, фэнтези, фантастика | Канада , США
[8] Левша | детектив, приключения, фантастика | Россия
[9] Крик 7 | триллер, ужасы | Канада , США
[10] Казнить нельзя помиловать | фантастика, боевик, триллер, детектив | Россия , США
[11] Грозовой перевал | драма, мелодрама | США , Великобритания
[12] Проект «Конец света» | драма, триллер, фантастика | США
[13] Три богатыря и свет клином | семейный, приключения, фэнтези, комедия, мультфильм | Россия
[14] Доспехи | приключения, комедия, драма, боевик, фэнтези | Франция
[15] Битва за битвой | криминал, драма, триллер, боевик | США
[16] Зараза | комедия, ужасы | Марокко , Италия , Великобритания , Франция , США
[17] 28 лет спустя: Часть II. Храм костей | ужасы | США , Великобритания
[18] Волчок | комедия, приключения | Россия
[19] Тайна древней гробницы | приключения, боевик, фэнтези | Китай
[20] Зверополис 2 | семейный, приключения, детектив, комедия, мультфильм | США
[21] Трансформация | боевик, фантастика | США , ЮАР
[22] Опасный дуэт | криминал, детектив, комедия, боевик | США , Новая Зеландия
[23] Гренландия 2: Миграция | приключения, триллер, боевик, фантастика | США , Великобритания
[24] Губка Боб: В поисках квадратных штанов | семейный, приключения, комедия, фэнтези, мультфильм | США
[25] Хищник: Планета смерти | боевик, фантастика | Германия , Канада , Новая Зеландия , Австралия , США
[26] Вердикт | детектив, криминал, драма, триллер, боевик | Корея Южная , Индонезия
[27] Иллюзия обмана 3 | криминал, триллер | Венгрия , Канада , ОАЭ , США
[28] Утёс | боевик | США
[29] Синий кит | детектив, триллер | Казахстан
[30] Лакомый кусок | боевик, криминал, триллер | США
[31] Грешники | музыка, ужасы | Канада , Австралия , США
[32] Сталкер. Тень Чернобыля | боевик, фантастика | США
[33] Несвятая Валентина | мелодрама, комедия | Россия
[34] Трофей | триллер | Россия
[35] Тропа гнева | боевик | Таджикистан , Россия
[36] Гадкий я 4 | семейный, приключения, криминал, комедия, фантастика, мультфильм | США
[37] Кей-поп-охотницы на демонов | боевик, музыка, комедия, фэнтези, мультфильм | США
[38] Холостяк в Италии | комедия, мелодрама | США
[39] Главный герой | мелодрама, комедия, боевик, фантастика | Канада , США
[40] Пять ночей с Фредди 2 | ужасы | Канада , США
[41] Очень страшное кино | ужасы, комедия | США
[42] Август | история, военный, триллер | Россия
[43] Выход 8 | драма, ужасы | Япония
[44] Шерлок Холмс | детектив, криминал, комедия, драма, триллер, приключения, боевик | Германия , США
[45] Дэдпул и Росомаха | приключения, комедия, боевик, фантастика | Канада , Новая Зеландия , Великобритания , США
[46] Одна миля: Глава первая | приключения, драма, триллер, боевик | США
[47] Война будущего | ужасы, боевик, фантастика | США
[48] Анаконда | приключения, комедия, боевик | США
[49] Первому игроку приготовиться | приключения, боевик, фантастика | Австралия , Япония , Великобритания , Канада , Сингапур , Индия , США
[50] F1 | спорт, драма | США
[51] Смотри в оба | триллер, фантастика, ужасы | США
[52] Как заработать на убийстве | криминал, комедия, триллер | Бельгия , Франция
[53] Шрэк | семейный, приключения, комедия, мелодрама, фэнтези, мультфильм | США
[54] Шальная императрица | приключения, фэнтези, комедия | Россия
[55] Босс-молокосос | семейный, приключения, комедия, мультфильм | США
[56] Убийца в петле времени | криминал, фантастика, триллер | США
[57] Человек-паук: Нет пути домой | фэнтези, приключения, боевик, фантастика | США
[58] В мгновение ока | драма, фантастика | США
[59] Аватар: Путь воды | приключения, боевик, фэнтези, фантастика | США
[60] Пираты Карибского моря: Проклятие Черной жемчужины | приключения, боевик, фэнтези | США
[61] На деревню дедушке | семейный, комедия | Россия
[62] Ущелье | мелодрама, боевик, фантастика | США , Великобритания
[63] Дюна | приключения, драма, боевик, фантастика | Венгрия , Канада , США
[64] Гарри Поттер и философский камень | семейный, приключения, фэнтези | США , Великобритания
[65] Достать ножи: Воскрешение покойника | криминал, комедия, детектив | США
[66] Завербованный | триллер, боевик | Россия
[67] Пункт назначения: Новый аттракцион | ужасы | США
[68] Игра со смертью | ужасы | Новая Зеландия , Аргентина
[69] Мстители: Финал | приключения, драма, боевик, фантастика | США
[70] Тёща | комедия | Россия
[71] Босс-молокосос 2 | семейный, приключения, комедия, мультфильм | США
[72] Дюна: Часть вторая | приключения, драма, боевик, фантастика | Гамбия , Иордания , Новая Зеландия , Италия , Венгрия , ОАЭ , Канада , США
[73] Мстители: Война бесконечности | приключения, боевик, фантастика | США
[74] Очень страшное кино 2 | комедия, ужасы | США
[75] Девушка и море | мелодрама, драма, биография, спорт | Франция , Великобритания , Италия , Венгрия , США
[76] Царевна-лягушка | фэнтези, приключения, семейный | Россия
[77] Здесь был Юра | музыка, комедия, драма | Россия
[78] Морской бой | приключения, триллер, боевик, фантастика | США , Япония
[79] Зверополис | семейный, приключения, детектив, комедия, мультфильм | США
[80] Шрэк 2 | семейный, приключения, комедия, мелодрама, фэнтези, мультфильм | США
[81] Мой любимый двортерьер | семейный | Австралия
[82] Горыныч | семейный, приключения, фэнтези | Россия
[83] Кит-убийца | детектив, триллер, боевик, фантастика, ужасы | Великобритания , США , Австралия
[84] 28 лет спустя | боевик, ужасы | США , Канада , Великобритания
[85] Бугония | фантастика, комедия, драма | Ирландия , Канада , Корея Южная , США
[86] Чебурашка | фэнтези, комедия, семейный | Россия
[87] Веном: Последний танец | ужасы, боевик, фантастика | Канада , Великобритания , США
[88] Мадагаскар | семейный, приключения, комедия, мультфильм | Великобритания , Канада , США
[89] Форсаж | криминал, триллер, боевик | Германия , США
[90] Старикам тут не место | вестерн, криминал, драма, триллер | США
[91] Ледниковый период | семейный, приключения, комедия, мультфильм | США
[92] Отпуск на двоих | мелодрама | США
[93] Властелин колец: Братство кольца | боевик, драма, приключения, фэнтези | США , Новая Зеландия
[94] Тачки | спорт, семейный, приключения, комедия, мультфильм | США
[95] Цепной пёс | криминал, триллер, боевик | Таиланд
[96] Зачетная принцесса | приключения, комедия, фэнтези | Германия
[97] Аквамен и потерянное царство | приключения, боевик, фэнтези, фантастика | США
[98] Банды Лондона | криминал, комедия, драма | Великобритания
[99] Лило и Стич | семейный, комедия, фантастика | Канада , Австралия , США
[100] 1+1 | комедия, драма | Франция
[101] Мстители | приключения, фэнтези, боевик, фантастика | США
[102] 28 дней спустя | драма, триллер, ужасы | США , Великобритания
[103] Третий лишний | комедия | США
[104] Гадкий я | семейный, приключения, криминал, комедия, фантастика, мультфильм | Франция , США
[105] Матрица | боевик, фантастика | Австралия , США
[106] Minecraft в кино | боевик, приключения, комедия, фэнтези | Канада , Новая Зеландия , США , Швеция
[107] Пираты Карибского моря: Сундук мертвеца | приключения, боевик, фэнтези | США
[108] Я краснею | семейный, комедия, фэнтези, мультфильм | Канада , США
[109] Рататуй | драма, фэнтези, семейный, комедия, приключения, мультфильм | США
[110] Мастер | криминал, боевик | США , Великобритания
[111] Аватар | приключения, драма, боевик, фантастика | Великобритания , США
[112] GOAT: Мечтай по-крупному | спорт, семейный, приключения, комедия, боевик, мультфильм | Сингапур , Япония , Бразилия , США
[113] Мортал Комбат | фантастика, фэнтези, боевик | США
[114] Послезавтра | приключения, драма, триллер, фантастика | США
[115] За Палыча! | военный, комедия | Россия
[116] Мир Юрского периода: Возрождение | приключения, боевик, фантастика | Тайвань , Индия , Мальта , Великобритания , США
[117] Кунг-фу Панда | семейный, приключения, комедия, боевик, фэнтези, мультфильм | США
[118] Гарри Поттер и Тайная комната | семейный, приключения, фэнтези | США , Великобритания
[119] Железный человек | приключения, боевик, фантастика | Канада , США
[120] Трансформеры | боевик, фантастика | США
[121] Как приручить дракона | семейный, приключения, фэнтези | Канада , Исландия , Ирландия , Великобритания , США
[122] Стражи Галактики | комедия, приключения, боевик, фантастика | Великобритания , США
[123] Дракон | драма, триллер, боевик, фантастика, ужасы | Ирландия
[124] Барбоскины Team | детский, мюзикл, мультфильм | Россия
[125] Моана 2 | семейный, приключения, комедия, фэнтези, мюзикл, мультфильм | Канада , США
[126] Элементарно | семейный, приключения, комедия, мелодрама, фэнтези, мультфильм | США
[127] Про людей и про войну | история, драма, военный | Россия
[128] Кот в сапогах 2: Последнее желание | фэнтези, приключения, комедия, мультфильм | Япония , США
[129] Очень страшное кино 5 | комедия | США
[130] Побег из плена | история, военный, боевик | США , Филиппины
[131] Гарри Поттер и узник Азкабана | семейный, приключения, фэнтези | США , Великобритания
[132] Очень страшное кино 3 | комедия | Канада , США
[133] (Не)искусственный интеллект | семейный, приключения, комедия, фантастика | Россия
[134] Шерлок Холмс: Игра теней | детектив, криминал, триллер, приключения, боевик | США
[135] Годзилла и Конг: Новая империя | боевик, фантастика | Австралия , США
[136] Папа может | семейный, комедия | Россия
[137] Одна миля: Глава вторая | драма, триллер, боевик | США
[138] Гадкий я 2 | семейный, приключения, криминал, комедия, фантастика, мультфильм | Франция , США
[139] Мальчишник в Вегасе | комедия | США
[140] Лучшие в аду | боевик, военный | Россия
[141] Бесславные ублюдки | военный, комедия, драма, боевик | США , Германия
[142] Человек-паук | приключения, боевик, фантастика | США
[143] Человек-паук: Возвращение домой | приключения, боевик, фантастика | США
[144] Рапунцель: Запутанная история | семейный, приключения, комедия, мелодрама, фэнтези, мюзикл, мультфильм | Япония , США
[145] Мадагаскар 2 | семейный, приключения, комедия, мультфильм | Великобритания , США
[146] Пчеловод | криминал, боевик | США , Великобритания
[147] Пираты Карибского моря: На краю света | фэнтези, боевик, приключения | США
[148] Интерстеллар | приключения, драма, фантастика | Канада , Великобритания , США
[149] Особое мнение | детектив, криминал, триллер, боевик, фантастика | США
[150] Обитель зла 2: Апокалипсис | фантастика, боевик, ужасы | Канада , Германия
[151] Живая сталь | семейный, боевик, фантастика | Индия , США
[152] Топ Ган: Мэверик | драма, боевик | США
[153] Гарри Поттер и Кубок огня | семейный, приключения, фэнтези | США , Великобритания
[154] Праздники | комедия | Россия
[155] Форсаж 10 | криминал, боевик | Исландия , Великобритания , Испания , Япония , Китай , США
[156] Волк с Уолл-стрит | комедия, биография, криминал, драма | США
[157] Джон Уик | криминал, триллер, боевик | Китай , США
[158] Корпорация монстров | семейный, приключения, комедия, фэнтези, мультфильм | США
[159] Три кота и море приключений | семейный, комедия, детский, мультфильм | Россия
[160] Папины дочки. Мама вернулась | семейный, комедия | Россия
[161] Электрический штат | комедия, боевик, драма, фантастика | США
[162] Всё заканчивается | драма, ужасы | США
[163] Крик | детектив, триллер, ужасы | США
[164] Веном | ужасы, боевик, фантастика | Китай , США
[165] Стражи Галактики. Часть 3 | приключения, комедия, боевик, фантастика | Канада , Франция , Новая Зеландия , США
[166] Пять ночей с Фредди | драма, ужасы | США
[167] Дэдпул | комедия, боевик | США
[168] Форсаж 5 | криминал, триллер, боевик | Япония , США
[169] Балерина | триллер, боевик | Венгрия , США
[170] Властелин колец: Две крепости | боевик, драма, приключения, фэнтези | США , Новая Зеландия
[171] Франкенштейн | драма, фантастика | Мексика , США
[172] Монстры на каникулах | семейный, комедия, фэнтези, мультфильм | Канада , США
[173] Гауа | фэнтези, ужасы | США , Испания
[174] Начало | детектив, драма, триллер, боевик, фантастика | Великобритания , США
[175] Железный человек 2 | приключения, боевик, фантастика | США
[176] Монстры на каникулах 3: Море зовёт | семейный, комедия, приключения, фэнтези, мультфильм | Корея Южная , США
[177] Три кота. Зимние каникулы | детский, мультфильм | Россия
[178] Тигр | драма, история, боевик, военный | Германия
[179] Люби меня, люби меня | мелодрама, драма | Италия
[180] Время | боевик, мелодрама, фантастика | США
[181] Верни меня из мёртвых | ужасы | Италия
[182] Флибубу | семейный, приключения, комедия, фэнтези, мультфильм | Финляндия
[183] Бойцовский клуб | криминал, драма, триллер | Германия , США
[184] Нейробатя | фантастика, комедия | Россия
[185] Хоббит: Нежданное путешествие | боевик, приключения, фэнтези | США , Новая Зеландия
[186] Оцепеневшие от страха | ужасы | Аргентина
[187] Человек-паук: Вдали от дома | приключения, комедия, боевик, фэнтези, фантастика | Италия , Канада , Австралия , Чехия , США
[188] Очень страшное кино 4 | комедия | США
[189] Соник 3 в кино | семейный, приключения, комедия, боевик, фэнтези, фантастика | Япония , США
[190] Невеста! | мелодрама, драма, фантастика | Франция , США
[191] Райя и последний дракон | семейный, приключения, комедия, драма, боевик, фэнтези, мультфильм | США
[192] Пираты Карибского моря: Мертвецы не рассказывают сказки | приключения, комедия, боевик, фэнтези | Канада , Великобритания , Австралия , США
[193] Кракен | драма, боевик, фантастика | Россия
[194] Мумия | боевик, приключения, фэнтези | США
[195] Сайлент Хилл | детектив, ужасы | США , Япония , Франция , Канада
[196] Холодное сердце | семейный, приключения, мелодрама, комедия, фэнтези, мюзикл, мультфильм | США
[197] Kingsman: Секретная служба | приключения, комедия, боевик | США , Великобритания
[198] Грань будущего | приключения, боевик, фантастика | Канада , США
[199] Железный человек 3 | приключения, боевик, фантастика | США
[200] Пираты Карибского моря: На странных берегах | комедия, фэнтези, боевик, приключения | Великобритания , США
[201] Шрэк Третий | семейный, приключения, комедия, мелодрама, фэнтези, мультфильм | Австралия , США
[202] Гадкий я 3 | семейный, приключения, криминал, комедия, фантастика, мультфильм | Япония , Франция , США
[203] Тихоокеанский рубеж | приключения, боевик, фантастика | Мексика , США
[204] Мстители: Эра Альтрона | приключения, боевик, фантастика | США
[205] Тачки 2 | спорт, семейный, приключения, криминал, комедия, фантастика, мультфильм | Япония , США
[206] Ешь! Борись! Люби! | комедия | Россия
[207] 10 жизней | семейный, комедия, фэнтези, мультфильм | США , Китай , Франция , Канада , Великобритания
[208] Кунг-фу Панда 2 | семейный, приключения, комедия, драма, боевик, фэнтези, мультфильм | Канада , США
[209] Маска | криминал, фэнтези, комедия | США
[210] Обитель зла | фантастика, боевик, ужасы | Германия , США
[211] Моана | семейный, приключения, комедия, фэнтези, мюзикл, мультфильм | США
[212] Головоломка 2 | фэнтези, семейный, комедия, мультфильм | США
[213] Пол: Секретный материальчик | приключения, комедия, фантастика | США , Великобритания
[214] Гарри Поттер и Принц-полукровка | семейный, приключения, фэнтези | США , Великобритания
[215] Ледниковый период 3: Эра динозавров | семейный, приключения, комедия, мультфильм | Канада , Великобритания , США
[216] Миньоны | семейный, приключения, криминал, комедия, фантастика, мультфильм | Франция , США
[217] Гарри Поттер и Орден Феникса | семейный, приключения, фэнтези | США , Великобритания
[218] Тайна Коко | музыка, семейный, приключения, комедия, фэнтези, мультфильм | Мексика , США
[219] Человек-паук 2 | приключения, боевик, фантастика | США
[220] Унесённые призраками | семейный, приключения, фэнтези, мультфильм, аниме | Япония
[221] Пингвины Мадагаскара | семейный, приключения, криминал, комедия, боевик, фантастика, мультфильм | Великобритания , США
[222] Обитель зла 3 | триллер, фантастика, боевик, ужасы | Великобритания , Австралия , Франция , США , Германия
[223] Гнев человеческий | триллер, боевик | США , Великобритания
[224] Нюрнберг | история, биография, военный, драма, триллер | Венгрия , США
[225] Форсаж 7 | приключения, криминал, боевик | США
[226] На помощь! | триллер | США
[227] Человек-паук: Через вселенные | семейный, приключения, комедия, боевик, фэнтези, фантастика, мультфильм | США , Канада
[228] Мадагаскар 3 | семейный, приключения, комедия, мультфильм | США
[229] Миссия невыполнима: Финальная расплата | приключения, триллер, боевик | США , Великобритания
[230] Темный рыцарь | драма, криминал, триллер, боевик, фантастика | Великобритания , США
[231] Властелин колец: Возвращение короля | боевик, драма, приключения, фэнтези | США , Новая Зеландия
[232] Круэлла | драма, криминал, комедия | Ирландия , Канада , Великобритания , США
[233] Тройной форсаж: Токийский дрифт | триллер, мелодрама, криминал, боевик | Германия , США
[234] Я – легенда | боевик, драма, ужасы | Великобритания , США
[235] Форсаж 4 | драма, триллер, боевик, криминал | США , Япония
[236] Бегущий человек | фантастика, боевик | США , Великобритания
[237] Я ругаюсь | драма, биография | Великобритания
[238] Бегущий в лабиринте | приключения, триллер, фантастика | Великобритания , США
[239] Мальчишник 2: Из Вегаса в Бангкок | комедия | США
[240] Иерархия | криминал, драма, боевик | США
[241] Тачки 3 | спорт, семейный, приключения, комедия, мультфильм | Япония , США
[242] Дьявол носит Prada | комедия, драма | Франция , США
[243] Двойной форсаж | криминал, триллер, боевик | Германия , США
[244] Истребитель демонов: Бесконечная крепость | боевик, фэнтези, мультфильм, аниме | Япония
[245] Головоломка | фэнтези, комедия, семейный, мультфильм | США
[246] Человек-паук: Паутина вселенных | семейный, приключения, боевик, фэнтези, фантастика, мультфильм | США
[247] Форсаж 6 | криминал, драма, триллер, боевик | Испания , Япония , США
[248] Исчезнувшая | детектив, драма, триллер | США
[249] Падение Луны | боевик, фантастика | Канада , Китай , США
[250] Семья в аренду | комедия, драма | США , Япония

 Файл 'zona_clean_data.csv' готов

In [11]:
df

,title,genre,year,country,rating,description
0,Ограбление в Лос-Анджелесе,"криминал, драма, триллер",2026,"США , Великобритания",6.7,Дерзкие ограбления неуловимого вора Дэвиса вдо...
1,"Удачи, веселья, не сдохни","боевик, драма, комедия, фантастика",2025,"США , Германия",7.0,Одним вечером в обычной закусочной появляется ...
2,Острые козырьки: Бессмертный человек,"история, драма, криминал",2026,"США , Франция , Великобритания",6.7,"1940-е годы, разгар Второй мировой войны. Спус..."
3,Чебурашка 2,"фэнтези, комедия, семейный",2025,Россия,7.6,"Уже год, как Чебурашка живет у Гены. Ушастик в..."
4,Король и Шут. Навсегда,"музыка, приключения, драма, комедия, фэнтези",2026,Россия,6.4,Панк-вселенной «Короля и Шута» грозит гибель. ...
...,...,...,...,...,...,...
245,Человек-паук: Паутина вселенных,"семейный, приключения, боевик, фэнтези, фантас...",2023,США,8.4,После воссоединения с Гвен Стейси дружелюбный ...
246,Форсаж 6,"криминал, драма, триллер, боевик",2013,"Испания , Япония , США",7.0,"После того как Доминик и Брайн побывали в Рио,..."
247,Исчезнувшая,"детектив, драма, триллер",2014,США,8.0,Всё было готово для празднования пятилетия суп...
248,Падение Луны,"боевик, фантастика",2022,"Канада , Китай , США",6.3,В 2011 году во время рядового ремонта спутника...
249,Семья в аренду,"комедия, драма",2025,"США , Япония",7.5,Не особо удачливый американский актёр Филлип у...

In [12]:
print("Количество нулевых значений в: ")
for i in result_list:
    print( i + " - " + str(result_list[i].count(None)))

Количество нулевых значений в:
title - 0
genre - 0
year - 0
country - 0
rating - 0
description - 0

# Парсинг с API

In [15]:
api_token = "M7HKBXS-FWH4JZB-NP91GN4-P0XEMSD"
api_url = "https://api.poiskkino.dev/v1/movie"

In [16]:
api_headers = {
    "X-API-KEY": api_token,
    "Content-Type": "application/json"
}

In [17]:
api_movies = {
    'title': [], 
    'genre': [], 
    'year': [], 
    'country': [], 
    'rating': [], 
    'description': []
}

In [18]:
for page in range(1, 6):
    params = {
        "page": page,
        "limit": 50,
        "selectFields": ["name", "year", "rating", "genres", "countries", "description"]
    }
    
    try:
        response = requests.get(api_url, headers=api_headers, params=params, timeout=10)
        data = response.json()
        
        if 'docs' in data:
            for item in data['docs']:
                name = item.get('name') or item.get('alternativeName') or "Без названия"
                
                genres_list = [g.get('name') for g in item.get('genres', [])]
                countries_list = [c.get('name') for c in item.get('countries', [])]
                
                api_movies['title'].append(name)
                api_movies['genre'].append(", ".join(genres_list) if genres_list else "Не указан")
                api_movies['year'].append(item.get('year', "N/A"))
                api_movies['country'].append(", ".join(countries_list) if countries_list else "Не указана")
                
                rating_val = item.get('rating', {})
                if isinstance(rating_val, dict):
                    api_movies['rating'].append(rating_val.get('kp', 0))
                else:
                    api_movies['rating'].append(rating_val)
                    
                api_movies['description'].append(item.get('description', "Нет описания"))
            
            print(f"API: Спарсили страницу {page} (всего {len(api_movies['title'])} фильмов)")
        else:
            print(f"Ошибка в структуре ответа API на странице {page}")
            
    except Exception as e:
        print(f"Ошибка при запросе к API: {e}")
    
    time.sleep(0.5)

df_api = pd.DataFrame(api_movies)
combined_df = pd.concat([df, df_api], ignore_index=True)
combined_df.drop_duplicates(subset=['title', 'year'], keep='first', inplace=True)
combined_df.to_csv('total_500_movies.csv', index=False, encoding='utf-8-sig')
print(f"После удаления дублей осталось фильмов: {len(combined_df)}")

API: Спарсили страницу 1 (всего 50 фильмов)
API: Спарсили страницу 2 (всего 100 фильмов)
API: Спарсили страницу 3 (всего 150 фильмов)
API: Спарсили страницу 4 (всего 200 фильмов)
API: Спарсили страницу 5 (всего 250 фильмов)
После удаления дублей осталось фильмов: 500

In [20]:
print("Количество нулевых значений в: ")
for i in api_movies:
    print( i + " - " + str(api_movies[i].count(None)))

Количество нулевых значений в:
title - 0
genre - 0
year - 0
country - 0
rating - 0
description - 0

In [19]:
combined_df

,title,genre,year,country,rating,description
0,Ограбление в Лос-Анджелесе,"криминал, драма, триллер",2026,"США , Великобритания",6.7,Дерзкие ограбления неуловимого вора Дэвиса вдо...
1,"Удачи, веселья, не сдохни","боевик, драма, комедия, фантастика",2025,"США , Германия",7.0,Одним вечером в обычной закусочной появляется ...
2,Острые козырьки: Бессмертный человек,"история, драма, криминал",2026,"США , Франция , Великобритания",6.7,"1940-е годы, разгар Второй мировой войны. Спус..."
3,Чебурашка 2,"фэнтези, комедия, семейный",2025,Россия,7.6,"Уже год, как Чебурашка живет у Гены. Ушастик в..."
4,Король и Шут. Навсегда,"музыка, приключения, драма, комедия, фэнтези",2026,Россия,6.4,Панк-вселенной «Короля и Шута» грозит гибель. ...
...,...,...,...,...,...,...
495,Список Шиндлера,"биография, история, драма, военный",1993,США,8.851,"Оскар Шиндлер, член национал-социалистической ..."
496,Гордость и предубеждение,"драма, мелодрама",2005,"Великобритания, Франция, США",8.151,"Англия, конец XVIII века. Родители пятерых сес..."
497,Отряд самоубийц,"фантастика, боевик, фэнтези, приключения",2016,"США, Канада",6.104,Правительство решает дать команде суперзлодеев...
498,Постучись в мою Тверь,"комедия, мелодрама",2024,Россия,7.086,"Городская фифа Алиса приезжает в Тверь, чтобы ..."
499,Оно,"ужасы, фэнтези, драма, детектив",2017,"США, Канада",7.301,Когда в городке Дерри штата Мэн начинают пропа...